spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://192.168.91.132:8080/root/spring-cloud-config.git
          search-paths: respo
          username: root
          password: qq145040070043

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/